---
apiVersion: v1
kind: Service 
metadata:
  name: sd-service
spec:
  selector:
    app: filmesnode
  ports:
    - protocol: 'TCP'
      port: 3030
      targetPort: 3030
  type: LoadBalancer

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pg-config
  labels:
    app: postgres
data:
  POSTGRES_DB: db_project 
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: pg123

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sd-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: filmesnode
  template:
    metadata:
      labels:
        app: filmesnode
    spec:
      containers:
        - name: filmes-node
          image: florsousa/teste