apiVersion: v1
kind: Service 
metadata:
  name: sd-service
spec:
  selector:
    app: filmesnode
  ports:
    - protocol: 'TCP'
      port: 3030
      targetPort: 3030

  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sd-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: filmesnode
  template:
    metadata:
      labels:
        app: filmesnode
    spec:
      containers:
        - name: db-filmes
          image: florsousa/db_sd
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 5432
        - name: filmes-node
          image: florsousa/servidor_node
          resources:
            limits: 
              memory: "128Mi"
              cpu: "500m"
        
          